import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../models/pelanggan.dart';
import '../models/transaksi_kredit.dart';
import '../models/pembayaran.dart';
import '../providers/piutang_provider.dart';
import '../utils/formatter.dart';

class DetailPelangganScreen extends StatefulWidget{final Pelanggan pelanggan;const DetailPelangganScreen({super.key,required this.pelanggan});@override State<DetailPelangganScreen> createState()=>_DetailState();}
class _DetailState extends State<DetailPelangganScreen>{List<TransaksiKredit> rows=[];bool loading=true;@override void initState(){super.initState();_load();}Future<void> _load()async{final r=await context.read<PiutangProvider>().muatTransaksi(widget.pelanggan.id!);if(mounted)setState((){rows=r;loading=false;});}
Future<void> _transaksi()async{final key=GlobalKey<FormState>();final res=TextEditingController(),recv=TextEditingController(),city=TextEditingController(),amount=TextEditingController(),note=TextEditingController();DateTime date=DateTime.now();bool saving=false;await showModalBottomSheet(context:context,isScrollControlled:true,builder:(ctx)=>StatefulBuilder(builder:(ctx,set)=>Padding(padding:EdgeInsets.fromLTRB(16,8,16,MediaQuery.of(ctx).viewInsets.bottom+12),child:SingleChildScrollView(child:Form(key:key,child:Column(children:[Text('Tambah Transaksi Kredit',style:Theme.of(ctx).textTheme.titleLarge),TextFormField(controller:res,decoration:const InputDecoration(labelText:'Nomor Resi *'),validator:(v)=>v!.trim().isEmpty?'Wajib diisi':null),TextFormField(controller:recv,decoration:const InputDecoration(labelText:'Nama Penerima *'),validator:(v)=>v!.trim().isEmpty?'Wajib diisi':null),TextFormField(controller:city,decoration:const InputDecoration(labelText:'Kota Tujuan *'),validator:(v)=>v!.trim().isEmpty?'Wajib diisi':null),TextFormField(controller:amount,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Jumlah *'),validator:(v)=>int.tryParse(v!.replaceAll('.',''))==null?'Jumlah tidak valid':null),TextField(controller:note,decoration:const InputDecoration(labelText:'Catatan')),ListTile(title:Text(Formatter.tanggalPanjang(date)),trailing:const Icon(Icons.calendar_today),onTap:()async{final d=await showDatePicker(context:ctx,firstDate:DateTime(2000),lastDate:DateTime(2100),initialDate:date);if(d!=null)set(()=>date=d);}),ElevatedButton(onPressed:saving?null:()async{if(!key.currentState!.validate())return;set(()=>saving=true);try{await ctx.read<PiutangProvider>().tambahTransaksi(TransaksiKredit(pelangganId:widget.pelanggan.id!,tanggal:date,nomorResi:res.text.trim(),namaPenerima:recv.text.trim(),kotaTujuan:city.text.trim(),jumlah:int.parse(amount.text.replaceAll('.','')),catatan:note.text.trim().isEmpty?null:note.text.trim()));if(ctx.mounted)Navigator.pop(ctx);if(mounted)_load();}catch(e){if(ctx.mounted){set(()=>saving=false);ScaffoldMessenger.of(ctx).showSnackBar(SnackBar(content:Text('$e')));}}},child:saving?const CircularProgressIndicator():const Text('Simpan'))]))))));res.dispose();recv.dispose();city.dispose();amount.dispose();note.dispose();}
Future<void> _bayar(TransaksiKredit t)async{final c=TextEditingController();final note=TextEditingController();bool saving=false;await showDialog(context:context,builder:(ctx)=>StatefulBuilder(builder:(ctx,set)=>AlertDialog(title:Text('Pembayaran ${t.nomorResi}'),content:Column(mainAxisSize:MainAxisSize.min,children:[Text('Sisa: ${Formatter.rupiah(t.sisa)}'),TextField(controller:c,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Jumlah')),TextField(controller:note,decoration:const InputDecoration(labelText:'Keterangan'))]),actions:[TextButton(onPressed:()=>Navigator.pop(ctx),child:const Text('Batal')),ElevatedButton(onPressed:saving?null:()async{final n=int.tryParse(c.text.replaceAll('.',''));if(n==null||n<=0||n>t.sisa){ScaffoldMessenger.of(ctx).showSnackBar(const SnackBar(content:Text('Jumlah pembayaran tidak valid')));return;}set(()=>saving=true);try{await ctx.read<PiutangProvider>().tambahPembayaran(Pembayaran(transaksiId:t.id!,tanggal:DateTime.now(),jumlah:n,keterangan:note.text.trim().isEmpty?null:note.text.trim()));if(ctx.mounted)Navigator.pop(ctx);if(mounted)_load();}catch(e){if(ctx.mounted){set(()=>saving=false);ScaffoldMessenger.of(ctx).showSnackBar(SnackBar(content:Text('$e')));}}},child:saving?const CircularProgressIndicator():const Text('Bayar'))]));c.dispose();note.dispose();}
@override Widget build(BuildContext c){return Scaffold(appBar:AppBar(title:Text(widget.pelanggan.nama)),floatingActionButton:FloatingActionButton(onPressed:_transaksi,child:const Icon(Icons.add)),body:loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:_load,child:ListView.builder(itemCount:rows.length,itemBuilder:(c,i){final t=rows[i];return Card(child:ListTile(title:Text(t.nomorResi),subtitle:Text('${t.namaPenerima} • ${t.kotaTujuan}\n${Formatter.tanggalPendek(t.tanggal)}'),isThreeLine:true,trailing:Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.end,children:[Text(Formatter.rupiah(t.sisa),style:const TextStyle(fontWeight:FontWeight.bold)),if(!t.lunas)TextButton(onPressed:()=>_bayar(t),child:const Text('Bayar'))]),onLongPress:()=>showModalBottomSheet(context:c,builder:(_)=>ListTile(leading:const Icon(Icons.delete),title:const Text('Hapus transaksi'),onTap:()async{Navigator.pop(c);final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('Hapus transaksi?'),content:const Text('Riwayat pembayaran juga akan terhapus.'),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Batal')),TextButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Hapus'))]));if(ok==true&&mounted){await context.read<PiutangProvider>().hapusTransaksi(t.id!);_load();}})));})));}}
