import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../providers/piutang_provider.dart';
import '../utils/formatter.dart';
import 'pelanggan_screen.dart';
import 'laporan_screen.dart';

class HomeScreen extends StatefulWidget { const HomeScreen({super.key}); @override State<HomeScreen> createState()=>_HomeScreenState(); }
class _HomeScreenState extends State<HomeScreen>{ Map<String,int>? summary; @override void initState(){super.initState(); _load(); WidgetsBinding.instance.addPostFrameCallback((_){context.read<PiutangProvider>().muatPelanggan();});} Future<void> _load() async {final s=await context.read<PiutangProvider>().ringkasanTotal();if(mounted)setState(()=>summary=s);} @override Widget build(BuildContext c){final s=summary;return Scaffold(appBar:AppBar(title:const Text('Piutang Usaha'),actions:[IconButton(onPressed:()async{try{await c.read<PiutangProvider>().backupDatabase();}catch(e){if(c.mounted)ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text('$e')));}},icon:const Icon(Icons.backup))]),body:RefreshIndicator(onRefresh:_load,child:ListView(padding:const EdgeInsets.all(16),children:[_card('Total Kredit',s?['total_kredit']??0),_card('Total Dibayar',s?['total_dibayar']??0),_card('Sisa Piutang',s?['sisa_piutang']??0),const SizedBox(height:12),ListTile(leading:const Icon(Icons.people),title:const Text('Pelanggan'),subtitle:const Text('Kelola pelanggan dan transaksi'),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const PelangganScreen())).then((_){_load();c.read<PiutangProvider>().muatPelanggan();})),ListTile(leading:const Icon(Icons.assessment),title:const Text('Laporan'),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const LaporanScreen())).then((_){_load();})]))));} Widget _card(String title,int value)=>Card(child:ListTile(title:Text(title),trailing:Text(Formatter.rupiah(value),style:const TextStyle(fontWeight:FontWeight.bold,fontSize:18)))); }
