import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../providers/piutang_provider.dart';
import '../services/export_service.dart';
import '../utils/formatter.dart';
import 'report_header_settings_screen.dart';

class LaporanScreen extends StatefulWidget { const LaporanScreen({super.key}); @override State<LaporanScreen> createState()=>_LaporanScreenState(); }
class _LaporanScreenState extends State<LaporanScreen>{
 DateTime dari=DateTime(DateTime.now().year,DateTime.now().month,1),sampai=DateTime.now(); List<Map<String,dynamic>> rows=[]; List<Map<String,dynamic>> payments=[]; bool loading=false,exporting=false;
 String _friendlyError(Object e)=>e.toString().replaceFirst(RegExp(r'^Exception:\s*'),'');
 Future<void> _load()async{if(dari.isAfter(sampai)){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Tanggal mulai tidak boleh lebih besar dari tanggal akhir.')));return;}if(mounted)setState(()=>loading=true);try{final provider=context.read<PiutangProvider>();final r=await provider.rekapPeriode(dari,sampai);final p=await provider.pembayaranPeriode(dari,sampai);if(!mounted)return;setState((){rows=r;payments=p;});}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(_friendlyError(e))));}finally{if(mounted)setState(()=>loading=false);}}
 Future<void> _pick(bool start)async{final selected=await showDatePicker(context:context,initialDate:start?dari:sampai,firstDate:DateTime(2000),lastDate:DateTime(2100));if(selected==null||!mounted)return;setState(()=>start?dari=selected:sampai=selected);}
 Future<void> _exportPdf()async{if(exporting)return;setState(()=>exporting=true);try{await ExportService.exportRekapKePdf(rows,dari,sampai);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Gagal mengekspor PDF: ${_friendlyError(e)}')));}finally{if(mounted)setState(()=>exporting=false);}}
 Future<void> _exportExcel()async{if(exporting)return;setState(()=>exporting=true);try{await ExportService.exportRekapKeExcel(rows);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Gagal mengekspor Excel: ${_friendlyError(e)}')));}finally{if(mounted)setState(()=>exporting=false);}}
 @override void initState(){super.initState();WidgetsBinding.instance.addPostFrameCallback((_){if(mounted)_load();});}
 @override Widget build(BuildContext context){final theme=Theme.of(context),scheme=theme.colorScheme;final totalKredit=rows.fold<int>(0,(s,r)=>s+(r['jumlah'] as num).toInt());final totalPembayaran=payments.fold<int>(0,(s,r)=>s+(r['jumlah'] as num).toInt());return Scaffold(appBar:AppBar(title:const Text('Laporan'),actions:[IconButton(onPressed:exporting?null:()async{await Navigator.push(context,MaterialPageRoute(builder:(_)=>const ReportHeaderSettingsScreen()));},tooltip:'Header laporan',icon:const Icon(Icons.business_outlined)),IconButton(onPressed:rows.isEmpty||exporting?null:_exportPdf,tooltip:'PDF',icon:const Icon(Icons.picture_as_pdf)),IconButton(onPressed:rows.isEmpty||exporting?null:_exportExcel,tooltip:'Excel',icon:const Icon(Icons.table_view))]),body:loading?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.all(12),children:[Card(child:Row(children:[Expanded(child:ListTile(title:const Text('Dari'),subtitle:Text('Pilih tanggal'),onTap:()=>_pick(true))),Expanded(child:ListTile(title:const Text('Sampai'),subtitle:Text('Pilih tanggal'),onTap:()=>_pick(false))),IconButton(onPressed:_load,tooltip:'Muat ulang',icon:const Icon(Icons.refresh))])),Card(child:ListTile(title:const Text('Kredit pada periode'),trailing:Text(Formatter.rupiah(totalKredit),style:TextStyle(color:scheme.primary,fontWeight:FontWeight.w700)))),Card(child:ListTile(title:const Text('Pembayaran diterima pada periode'),trailing:Text(Formatter.rupiah(totalPembayaran),style:TextStyle(color:scheme.primary,fontWeight:FontWeight.w700)))),const SizedBox(height:8),Text('Rekap transaksi',style:theme.textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:8),if(rows.isEmpty)Card(child:Padding(padding:const EdgeInsets.symmetric(vertical:28,horizontal:20),child:Column(children:[Icon(Icons.receipt_long_outlined,size:48,color:scheme.primary),const SizedBox(height:12),Text('Belum ada transaksi pada periode ini.',style:theme.textTheme.titleMedium,textAlign:TextAlign.center),const SizedBox(height:6),Text('Coba ubah rentang tanggal lalu tekan tombol refresh.',style:theme.textTheme.bodyMedium,textAlign:TextAlign.center)])))else...rows.map((row){final kredit=(row['jumlah'] as num).toInt(),dibayar=(row['total_dibayar'] as num).toInt(),dibayarPeriode=(row['dibayar_periode'] as num?)?.toInt()??0;return Card(child:ListTile(title:Text('${row['nama_pelanggan']} • ${row['nomor_resi']}',maxLines:1,overflow:TextOverflow.ellipsis),subtitle:Text('${row['nama_penerima']} • ${row['kota_tujuan']}\nDibayar periode: ${Formatter.rupiah(dibayarPeriode)}',maxLines:2,overflow:TextOverflow.ellipsis),trailing:Text(Formatter.rupiah(kredit-dibayar),maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontWeight:FontWeight.w700))));})]));}
}