import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../providers/piutang_provider.dart';
import '../services/export_service.dart';
import '../utils/formatter.dart';

class LaporanScreen extends StatefulWidget{const LaporanScreen({super.key});@override State<LaporanScreen> createState()=>_LaporanState();}
class _LaporanState extends State<LaporanScreen>{DateTime dari=DateTime(DateTime.now().year,DateTime.now().month,1),sampai=DateTime.now();List<Map<String,dynamic>> rows=[];List<Map<String,dynamic>> payments=[];bool loading=false;
Future<void> _load()async{if(dari.isAfter(sampai)){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Tanggal mulai tidak boleh lebih besar dari tanggal akhir.')));return;}setState(()=>loading=true);try{final p=context.read<PiutangProvider>();final a=await p.rekapPeriode(dari,sampai),b=await p.pembayaranPeriode(dari,sampai);if(mounted)setState((){rows=a;payments=b;});}finally{if(mounted)setState(()=>loading=false);}}
Future<void> _pick(bool start)async{final d=await showDatePicker(context:context,initialDate:start?dari:sampai,firstDate:DateTime(2000),lastDate:DateTime(2100));if(d!=null&&mounted)setState((){if(start)dari=d;else sampai=d;});}
@override void initState(){super.initState();WidgetsBinding.instance.addPostFrameCallback((_){_load();});}
@override Widget build(BuildContext c){final totalK=rows.fold<int>(0,(s,r)=>s+(r['jumlah'] as num).toInt());final totalP=payments.fold<int>(0,(s,r)=>s+(r['jumlah'] as num).toInt());return Scaffold(appBar:AppBar(title:const Text('Laporan'),actions:[IconButton(onPressed:rows.isEmpty?null:()=>ExportService.exportRekapKePdf(rows,dari,sampai),icon:const Icon(Icons.picture_as_pdf)),IconButton(onPressed:rows.isEmpty?null:()=>ExportService.exportRekapKeExcel(rows),icon:const Icon(Icons.table_view))]),body:loading?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.all(12),children:[Row(children:[Expanded(child:ListTile(title:const Text('Dari'),subtitle:Text(Formatter.tanggalPendek(dari)),onTap:()=>_pick(true))),Expanded(child:ListTile(title:const Text('Sampai'),subtitle:Text(Formatter.tanggalPendek(sampai)),onTap:()=>_pick(false))),IconButton(onPressed:_load,icon:const Icon(Icons.refresh))]),Card(child:ListTile(title:const Text('Kredit pada periode'),trailing:Text(Formatter.rupiah(totalK))),),Card(child:ListTile(title:const Text('Pembayaran diterima pada periode'),trailing:Text(Formatter.rupiah(totalP))),),const SizedBox(height:8),const Text('Rekap transaksi',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),...rows.map((r){final k=(r['jumlah'] as num).toInt(),d=(r['total_dibayar'] as num).toInt(),dp=(r['dibayar_periode'] as num?)?.toInt()??0;return Card(child:ListTile(title:Text('${r['nama_pelanggan']} • ${r['nomor_resi']}'),subtitle:Text('${r['nama_penerima']} • ${r['kota_tujuan']}\nDibayar periode: ${Formatter.rupiah(dp)}'),trailing:Text(Formatter.rupiah(k-d)));})]) );}
}
