import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../models/pelanggan.dart';
import '../providers/piutang_provider.dart';
import '../utils/formatter.dart';
import 'detail_pelanggan_screen.dart';

class PelangganScreen extends StatefulWidget {
  const PelangganScreen({super.key});
  @override State<PelangganScreen> createState() => _PelangganScreenState();
}

class _PelangganScreenState extends State<PelangganScreen> {
  @override void initState() { super.initState(); WidgetsBinding.instance.addPostFrameCallback((_) { if (mounted) context.read<PiutangProvider>().muatPelanggan(); }); }
  String _friendlyError(Object e) { final text=e.toString(); return text.startsWith('Exception: ')?text.substring(11):text; }

  Future<void> _form({Pelanggan? old}) async {
    final name=TextEditingController(text:old?.nama??''),phone=TextEditingController(text:old?.noHp??''),address=TextEditingController(text:old?.alamat??'');
    final formKey=GlobalKey<FormState>(); bool saving=false;
    await showModalBottomSheet<void>(context:context,isScrollControlled:true,builder:(ctx)=>StatefulBuilder(builder:(ctx,setSheetState)=>Padding(padding:EdgeInsets.fromLTRB(16,16,16,MediaQuery.of(ctx).viewInsets.bottom+16),child:Form(key:formKey,child:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[Text(old==null?'Tambah Pelanggan':'Edit Pelanggan',style:Theme.of(ctx).textTheme.titleLarge),const SizedBox(height:16),TextFormField(controller:name,decoration:const InputDecoration(labelText:'Nama *'),validator:(v)=>v==null||v.trim().isEmpty?'Nama wajib diisi':null),const SizedBox(height:12),TextField(controller:phone,decoration:const InputDecoration(labelText:'No. HP')),const SizedBox(height:12),TextField(controller:address,decoration:const InputDecoration(labelText:'Alamat')),const SizedBox(height:16),SizedBox(width:double.infinity,child:ElevatedButton(onPressed:saving?null:()async{if(!formKey.currentState!.validate())return;setSheetState(()=>saving=true);try{final provider=ctx.read<PiutangProvider>();if(old==null){await provider.tambahPelanggan(Pelanggan(nama:name.text.trim(),noHp:phone.text.trim().isEmpty?null:phone.text.trim(),alamat:address.text.trim().isEmpty?null:address.text.trim()));}else{await provider.updatePelanggan(old.copyWith(nama:name.text.trim(),noHp:phone.text.trim(),alamat:address.text.trim()));}if(ctx.mounted)Navigator.pop(ctx);}catch(e){if(ctx.mounted){setSheetState(()=>saving=false);ScaffoldMessenger.of(ctx).showSnackBar(SnackBar(content:Text(_friendlyError(e))));}}},child:saving?const SizedBox(height:20,width:20,child:CircularProgressIndicator(strokeWidth:2)):const Text('Simpan'))]))))));
    name.dispose();phone.dispose();address.dispose();
  }

  Future<void> _delete(Pelanggan pelanggan) async {final ok=await showDialog<bool>(context:context,builder:(dialogContext)=>AlertDialog(title:const Text('Hapus pelanggan?'),content:Text('Semua transaksi dan pembayaran ${pelanggan.nama} akan ikut terhapus.'),actions:[TextButton(onPressed:()=>Navigator.pop(dialogContext,false),child:const Text('Batal')),TextButton(onPressed:()=>Navigator.pop(dialogContext,true),child:const Text('Hapus'))]));if(ok!=true||!mounted)return;try{await context.read<PiutangProvider>().hapusPelanggan(pelanggan.id!);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(_friendlyError(e))));}}
  Future<void> _openDetail(Pelanggan pelanggan) async {await Navigator.of(context).push(MaterialPageRoute(builder:(_)=>DetailPelangganScreen(pelanggan:pelanggan)));if(!mounted)return;await context.read<PiutangProvider>().muatPelanggan();}

  @override Widget build(BuildContext context){final theme=Theme.of(context),scheme=theme.colorScheme;return Scaffold(appBar:AppBar(title:const Text('Pelanggan')),floatingActionButton:FloatingActionButton(onPressed:_form,child:const Icon(Icons.add)),body:Consumer<PiutangProvider>(builder:(context,provider,_){if(provider.loading)return const Center(child:CircularProgressIndicator());if(provider.daftarPelanggan.isEmpty)return Center(child:Padding(padding:const EdgeInsets.all(32),child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(Icons.people_outline,size:52,color:scheme.primary),const SizedBox(height:12),Text('Belum ada pelanggan.',style:theme.textTheme.titleMedium),const SizedBox(height:6),Text('Tambahkan pelanggan untuk mulai mencatat transaksi.',textAlign:TextAlign.center,style:theme.textTheme.bodyMedium)])));return ListView.separated(itemCount:provider.daftarPelanggan.length,separatorBuilder:(_,__)=>const Divider(height:1),itemBuilder:(context,index){final pelanggan=provider.daftarPelanggan[index],sisa=provider.sisaPelanggan(pelanggan.id!),hasDebt=sisa>0,statusColor=hasDebt?scheme.error:scheme.primary;return ListTile(leading:CircleAvatar(child:Text(pelanggan.nama.isEmpty?'?':pelanggan.nama[0].toUpperCase())),title:Text(pelanggan.nama,maxLines:1,overflow:TextOverflow.ellipsis),subtitle:Text(pelanggan.noHp??'-',maxLines:1,overflow:TextOverflow.ellipsis),trailing:Row(mainAxisSize:MainAxisSize.min,children:[Icon(hasDebt?Icons.warning_amber_rounded:Icons.check_circle_outline,size:18,color:statusColor),const SizedBox(width:6),Text(Formatter.rupiah(sisa),maxLines:1,overflow:TextOverflow.ellipsis,style:TextStyle(fontWeight:FontWeight.bold,color:statusColor))]),onTap:()=>_openDetail(pelanggan),onLongPress:()=>showModalBottomSheet<void>(context:context,builder:(sheetContext)=>SafeArea(child:Wrap(children:[ListTile(leading:const Icon(Icons.edit),title:const Text('Edit'),onTap:(){Navigator.pop(sheetContext);_form(old:pelanggan);}),ListTile(leading:const Icon(Icons.delete),title:const Text('Hapus'),onTap:(){Navigator.pop(sheetContext);_delete(pelanggan);})]))));}}));}
}
