import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../models/pelanggan.dart';
import '../providers/piutang_provider.dart';
import '../utils/formatter.dart';
import 'detail_pelanggan_screen.dart';

class PelangganScreen extends StatefulWidget{const PelangganScreen({super.key});@override State<PelangganScreen> createState()=>_PelangganScreenState();}
class _PelangganScreenState extends State<PelangganScreen>{@override void initState(){super.initState();WidgetsBinding.instance.addPostFrameCallback((_){context.read<PiutangProvider>().muatPelanggan();});}
Future<void> _form({Pelanggan? old}) async {final name=TextEditingController(text:old?.nama??''),phone=TextEditingController(text:old?.noHp??''),address=TextEditingController(text:old?.alamat??'');final key=GlobalKey<FormState>();bool saving=false;await showModalBottomSheet(context:context,isScrollControlled:true,builder:(ctx)=>StatefulBuilder(builder:(ctx,set){return Padding(padding:EdgeInsets.fromLTRB(16,16,16,MediaQuery.of(ctx).viewInsets.bottom+16),child:Form(key:key,child:Column(mainAxisSize:MainAxisSize.min,children:[Text(old==null?'Tambah Pelanggan':'Edit Pelanggan',style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold)),TextFormField(controller:name,decoration:const InputDecoration(labelText:'Nama *'),validator:(v)=>v==null||v.trim().isEmpty?'Nama wajib diisi':null),TextField(controller:phone,decoration:const InputDecoration(labelText:'No. HP')),TextField(controller:address,decoration:const InputDecoration(labelText:'Alamat')),const SizedBox(height:12),ElevatedButton(onPressed:saving?null:()async{if(!key.currentState!.validate())return;set(()=>saving=true);try{final p=ctx.read<PiutangProvider>();if(old==null)await p.tambahPelanggan(Pelanggan(nama:name.text.trim(),noHp:phone.text.trim().isEmpty?null:phone.text.trim(),alamat:address.text.trim().isEmpty?null:address.text.trim()));else await p.updatePelanggan(old.copyWith(nama:name.text.trim(),noHp:phone.text.trim(),alamat:address.text.trim()));if(ctx.mounted)Navigator.pop(ctx);}catch(e){if(ctx.mounted){set(()=>saving=false);ScaffoldMessenger.of(ctx).showSnackBar(SnackBar(content:Text('$e')));}}},child:saving?const CircularProgressIndicator():const Text('Simpan'))]))));});});name.dispose();phone.dispose();address.dispose();}
Future<void> _delete(Pelanggan p)async{final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('Hapus pelanggan?'),content:Text('Semua transaksi dan pembayaran ${p.nama} akan ikut terhapus.'),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Batal')),TextButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Hapus'))]));if(ok==true&&mounted){try{await context.read<PiutangProvider>().hapusPelanggan(p.id!);}catch(e){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e')));}}}
@override Widget build(BuildContext c){return Scaffold(appBar:AppBar(title:const Text('Pelanggan')),floatingActionButton:FloatingActionButton(onPressed:()=>_form(),child:const Icon(Icons.add)),body:Consumer<PiutangProvider>(builder:(c,p,_){if(p.loading)return const Center(child:CircularProgressIndicator());if(p.daftarPelanggan.isEmpty)return const Center(child:Text('Belum ada pelanggan.'));return ListView.builder(itemCount:p.daftarPelanggan.length,itemBuilder:(c,i){final x=p.daftarPelanggan[i],s=p.sisaPelanggan(x.id!);return ListTile(leading:CircleAvatar(child:Text(x.nama.isEmpty?'?':x.nama[0].toUpperCase())),title:Text(x.nama),subtitle:Text(x.noHp??'-'),trailing:Text(Formatter.rupiah(s),style:TextStyle(fontWeight:FontWeight.bold,color:s>0?Colors.red:Colors.green)),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>DetailPelangganScreen(pelanggan:x))).then((_){if(mounted)context.read<PiutangProvider>().muatPelanggan();}),onLongPress:()=>showModalBottomSheet(context:c,builder:(_)=>SafeArea(child:Wrap(children:[ListTile(leading:const Icon(Icons.edit),title:const Text('Edit'),onTap:(){Navigator.pop(c);_form(old:x);}),ListTile(leading:const Icon(Icons.delete),title:const Text('Hapus'),onTap:(){Navigator.pop(c);_delete(x);})])));});}));}}
