import 'dart:io';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import '../services/report_header_settings.dart';

class ReportHeaderSettingsScreen extends StatefulWidget { const ReportHeaderSettingsScreen({super.key}); @override State<ReportHeaderSettingsScreen> createState()=>_ReportHeaderSettingsScreenState(); }
class _ReportHeaderSettingsScreenState extends State<ReportHeaderSettingsScreen>{
 final companyController=TextEditingController(); final titleController=TextEditingController(); String? logoPath; bool loading=true,saving=false;
 @override void initState(){super.initState();_load();}
 Future<void> _load()async{final s=await ReportHeaderSettings.load();if(!mounted)return;companyController.text=s.companyName;titleController.text=s.reportTitle;setState((){logoPath=s.logoPath;loading=false;});}
 Future<void> _pickLogo()async{final r=await FilePicker.platform.pickFiles(type:FileType.custom,allowedExtensions:['png','jpg','jpeg']);if(!mounted||r==null||r.files.single.path==null)return;setState(()=>logoPath=r.files.single.path);}
 Future<void> _save()async{final company=companyController.text.trim(),title=titleController.text.trim();if(company.isEmpty||title.isEmpty){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Nama perusahaan dan judul laporan wajib diisi.')));return;}setState(()=>saving=true);try{final current=await ReportHeaderSettings.load();await current.save(companyName:company,reportTitle:title,logoPath:logoPath,removeLogo:logoPath==null);if(!mounted)return;ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Header laporan berhasil disimpan.')));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Gagal menyimpan: ${e.toString().replaceFirst('Exception: ','')}')));}finally{if(mounted)setState(()=>saving=false);}}
 Future<void> _reset()async{await ReportHeaderSettings.reset();if(!mounted)return;companyController.text=ReportHeaderSettings.defaultCompany;titleController.text=ReportHeaderSettings.defaultTitle;setState(()=>logoPath=null);ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Header dikembalikan ke pengaturan awal.')));}
 @override void dispose(){companyController.dispose();titleController.dispose();super.dispose();}
 @override Widget build(BuildContext context){final theme=Theme.of(context);return Scaffold(appBar:AppBar(title:const Text('Header Laporan')),body:loading?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.all(16),children:[Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text('Identitas Header',style:theme.textTheme.titleLarge),const SizedBox(height:6),Text('Pengaturan ini digunakan otomatis pada PDF dan Excel laporan pelanggan.',style:theme.textTheme.bodyMedium),const SizedBox(height:16),TextField(controller:companyController,textCapitalization:TextCapitalization.characters,decoration:const InputDecoration(labelText:'Nama Perusahaan',prefixIcon:Icon(Icons.business_outlined))),const SizedBox(height:12),TextField(controller:titleController,decoration:const InputDecoration(labelText:'Judul Laporan',prefixIcon:Icon(Icons.title_outlined))),const SizedBox(height:18),Text('Logo Perusahaan',style:theme.textTheme.titleMedium),const SizedBox(height:8),if(logoPath!=null&&File(logoPath!).existsSync())Container(height:120,padding:const EdgeInsets.all(12),decoration:BoxDecoration(border:Border.all(color:theme.colorScheme.outlineVariant),borderRadius:BorderRadius.circular(12)),child:Image.file(File(logoPath!),fit:BoxFit.contain))else Container(height:120,alignment:Alignment.center,decoration:BoxDecoration(border:Border.all(color:theme.colorScheme.outlineVariant),borderRadius:BorderRadius.circular(12)),child:const Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(Icons.image_outlined,size:40),SizedBox(height:6),Text('Belum ada logo')])),const SizedBox(height:10),OutlinedButton.icon(onPressed:_pickLogo,icon:const Icon(Icons.upload_file_outlined),label:Text(logoPath==null?'Pilih Logo':'Ganti Logo')),if(logoPath!=null)TextButton.icon(onPressed:()=>setState(()=>logoPath=null),icon:const Icon(Icons.delete_outline),label:const Text('Hapus Logo')),const SizedBox(height:16),FilledButton.icon(onPressed:saving?null:_save,icon:saving?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.save_outlined),label:const Text('Simpan Pengaturan')),TextButton(onPressed:saving?null:_reset,child:const Text('Kembalikan ke Default'))])))]));}
}